<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name = "gdgu_robot">

    <xacro:macro name="inertial_box" params="mass x y z *origin">
        <inertial>
            <xacro:insert_block name="origin"/>
            <mass value="${mass}"/>
            <inertia ixx="${(1/12) * mass * (y*y+z*z)}" ixy="0.0" ixz="0.0"
                    iyy="${(1/12) * mass * (x*x+z*z)}" iyz="0.0"
                    izz="${(1/12) * mass * (x*x+y*y)}" />
        </inertial>
    </xacro:macro>

    <xacro:macro name="inertial_sphere" params="mass radius *origin">
        <inertial>
            <xacro:insert_block name="origin"/>
            <mass value="${mass}"/>
            <inertia ixx="${(2/5) * mass * (radius*radius)}" ixy="0.0" ixz="0.0"
                    iyy="${(2/5) * mass * (radius*radius)}" iyz="0.0"
                    izz="${(2/5) * mass * (radius*radius)}" />
        </inertial>
    </xacro:macro>

    <xacro:macro name="inertial_cylinder" params="mass radius length *origin">
        <inertial>
            <xacro:insert_block name="origin"/>
            <mass value="${mass}"/>
            <inertia ixx="${(1/12) * mass * (3*radius*radius + length*length)}" ixy="0.0" ixz="0.0"
                    iyy="${(1/12) * mass * (3*radius*radius + length*length)}" iyz="0.0"
                    izz="${(1/2) * mass * (radius*radius)}" />
        </inertial>
    </xacro:macro>
    

    <xacro:property name="chassis_length" value="0.35"/>
    <xacro:property name="chassis_width" value="0.29"/>
    <xacro:property name="chassis_height" value="0.002"/>
    <xacro:property name="chassis_mass" value="2.0"/>
    <xacro:property name="wheel_radius" value="0.05"/>
    <xacro:property name="wheel_thickness" value="0.02"/>
    <xacro:property name="wheel_mass" value="0.5"/>
    <xacro:property name="wheel_offset_x" value="0.175"/>
    <xacro:property name="wheel_offset_y" value="0.155"/>
    <xacro:property name="wheel_offset_z" value="0.01"/>
    <xacro:property name="caster_wheel_radius" value="0.01"/>
    <xacro:property name="caster_wheel_mass" value="0.01"/>
    <xacro:property name="caster_wheel_offset_x" value="0.015"/>
    <xacro:property name="caster_wheel_offset_z" value="${wheel_offset_z - wheel_radius + caster_wheel_radius}"/>


    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <!-- BASE LINK -->

    <link name="base_link">

    </link>

    <!-- BASE_FOOTPRINT LINK -->

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">
    </link>


    <!-- CHASSIS LINK -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis_link"/>
        <origin xyz="${-wheel_offset_x} 0 ${-wheel_offset_z}"/>
    </joint>

    <link name="chassis_link">
        <visual>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis_link">
        <material>Gazebo/Orange</material>
    </gazebo>

    <!-- LEFT WHEEL LINK -->

    <joint name="left_wheel" type="continuous">
        <parent link="base_link"/>
        <child link="lfw_link"/>
        <origin xyz="0 ${wheel_offset_y} 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="lfw_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="lfw_link">
        <material>Gazebo/Blue</material>
    </gazebo>




    <!-- RIGHT WHEEL LINK -->

    <joint name="right_wheel" type="continuous">
        <parent link="base_link"/>
        <child link="rfw_link"/>
        <origin xyz="0 ${-wheel_offset_y} 0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="rfw_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="rfw_link">
        <material>Gazebo/Blue</material>
    </gazebo>

    <!--castor wheels-->

    <joint name="caster_wheel1_joint" type="fixed">
        <parent link="chassis_link"/>
        <child link="caster_wheel1_link"/>
        <origin xyz="${caster_wheel_offset_x} 0.125 ${caster_wheel_offset_z}"/>
    </joint>


    <link name="caster_wheel1_link">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="caster_wheel1_link">
        <material>Gazebo/Red</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

    <joint name="caster_wheel2_joint" type="fixed">
        <parent link="chassis_link"/>
        <child link="caster_wheel2_link"/>
        <origin xyz="${caster_wheel_offset_x} -0.125 ${caster_wheel_offset_z}"/>
    </joint>


    <link name="caster_wheel2_link">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="caster_wheel2_link">
        <material>Gazebo/Red</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

<joint name="caster_wheel3_joint" type="fixed">
        <parent link="chassis_link"/>
        <child link="caster_wheel3_link"/>
        <origin xyz="${caster_wheel_offset_x + 0.29} 0.125 ${caster_wheel_offset_z}"/>
    </joint>


    <link name="caster_wheel3_link">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="caster_wheel3_link">
        <material>Gazebo/Red</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

<joint name="caster_wheel4_joint" type="fixed">
        <parent link="chassis_link"/>
        <child link="caster_wheel4_link"/>
        <origin xyz="${caster_wheel_offset_x + 0.29} -0.125 ${caster_wheel_offset_z}"/>
    </joint>


    <link name="caster_wheel4_link">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="caster_wheel4_link">
        <material>Gazebo/Red</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

    <joint name="connector_cw1_joint" type="fixed">
        <parent link="caster_wheel1_link"/>
        <child link="connector_cw1_link"/>
        <origin xyz="0.0 0.0 0.02" rpy="0 0 0"/>
    </joint>
    <link name="connector_cw1_link">
        <visual>
            <geometry>
                <cylinder radius="0.005" length="0.022"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.005" length="0.022"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass = "0.1" radius = "0.005" length = "0.022">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- Connector for castor wheel 2 -->
    <joint name="connector_cw2_joint" type="fixed">
        <parent link="caster_wheel2_link"/>
        <child link="connector_cw2_link"/>
        <origin xyz="0.0 0.0 0.02" rpy="0 0 0"/>
    </joint>

    <link name="connector_cw2_link">
        <visual>
            <geometry>
                <cylinder radius="0.005" length="0.022"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.005" length="0.022"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass = "0.1" radius = "0.005" length = "0.022">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- Connector for castor wheel 3 -->
    <joint name="connector_cw3_joint" type="fixed">
        <parent link="caster_wheel3_link"/>
        <child link="connector_cw3_link"/>
        <origin xyz="0.0 0.0 0.02" rpy="0 0 0"/>
    </joint>
    <link name="connector_cw3_link">
        <visual>
            <geometry>
                <cylinder radius="0.005" length="0.022"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.005" length="0.022"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass = "0.1" radius = "0.005" length = "0.022">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- Connector for castor wheel 4 -->
    <joint name="connector_cw4_joint" type="fixed">
        <parent link="caster_wheel4_link"/>
        <child link="connector_cw4_link"/>
        <origin xyz="0.0 0.0 0.02" rpy="0 0 0"/>
    </joint>
    <link name="connector_cw4_link">
        <visual>
            <geometry>
                <cylinder radius="0.005" length="0.022"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.005" length="0.022"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass = "0.1" radius = "0.005" length = "0.022">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo>
        <plugin filename="gz-sim-diff-drive-system" name="gz::sim::systems::DiffDrive">

            <!--Wheel Info-->
            <left_joint>left_wheel</left_joint>
            <right_joint>right_wheel</right_joint> 
            <wheel_separation>0.31</wheel_separation>
            <wheel_radius>0.05</wheel_radius>
            
            <!--input-->
            <odom_publish_frequency>100</odom_publish_frequency>
            <topic>cmd_vel</topic>

            <!--output "what needs to be shown in the output"-->
            <odom_topic>odom</odom_topic>
            <!--limits "set according to the motor requirements"-->
            <max_linear_acceleration>1</max_linear_acceleration>
        </plugin>

        <plugin filename="gz-sim-joint-state-publisher-system" name="gz::sim::systems::JointStatePublisher">
            <topic>joint_states</topic>
            <joint_name>left_wheel</joint_name>
            <joint_name>right_wheel</joint_name>
        </plugin>  


    </gazebo>



</robot>